Исключение возникает при попытки изменить коллекцию во время итерации, что реализует fail-fast поведение при проведении итераций. 